service: ai-writer
frameworkVersion: '3'

provider:
  name: aws
  logRetentionInDays: 1
  runtime: nodejs18.x
  environment:
    SSM_PARAMETER_STORE_TTL: 60
    PARAMETERS_SECRETS_EXTENSION_HTTP_PORT: 9876
    OPENAI_PARAMETER_NAME: /openai/api-key
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - kms:Decrypt
          Resource: '*'

plugins:
  - serverless-esbuild
  - serverless-step-functions

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false

functions:
  fetchArticles:
    handler: src/steps/fetchArticles.handler
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
  extractArticleText:
    handler: src/steps/extractArticleText.handler
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
  summarizeArticle:
    handler: src/steps/summarizeArticle.handler
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
  publishArticles:
    handler: src/steps/publishArticles.handler
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2


stepFunctions:
  stateMachines:
    articleGenerator:
      # events:
      #   - schedule:
      #       rate: rate(10 minutes)
      #       enabled: true
      #       input:
      #         key1: value1
      #         key2: value2
      #         stageParams:
      #           stage: dev
      name: articleGenerator
      definition:
        Comment: "A article generated that summarizes daily news from ABC News"
        StartAt: FetchArticles
        States:
          FetchArticles:
            Type: Task
            Resource:
              Fn::GetAtt: [fetchArticles, Arn]
            Next: ExtractArticleText
          ExtractArticleText:
            Type: Task
            Resource:
              Fn::GetAtt: [extractArticleText, Arn]
            Next: SummarizeAll
          SummarizeAll:
            Type: Map
            Iterator:
              StartAt: SummarizeArticle
              States:
                SummarizeArticle:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [summarizeArticle, Arn]
                  End: true
            Next: PublishArticles
          PublishArticles:
            Type: Task
            Resource:
              Fn::GetAtt: [publishArticles, Arn]
            End: true
  validate: true
