name: Frontend Update

defaults:
  run:
    working-directory: frontend
    
on:
  schedule:
    # Run at 7:37 PM CST every day
    - cron:  '37 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cached Modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
      - name: Install
        run: npm i
      - name: Fetch Latest Articles
        run: npm run downloadArticles
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Commit Latest Articles
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "GithubAction: Updated Latest Articles"
            branch: main
            file_pattern: 'data/blog/*.mdx'
            commit_author: Author <actions@github.com>
            skip_dirty_check: false
            skip_fetch: false
            skip_checkout: false