name: Frontend Update

defaults:
  run:
    working-directory: frontend
    
on:
  schedule:
    # Run at 7:37 PM CST every day
    - cron:  '37 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cached Modules
      uses: actions/cache@v2
      with:
         path: '**/node_modules'
         key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
    - name: Install
      run: npm i
    - name: Fetch Latest Articles
      run: npm run downloadArticles
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Commit Latest Articles
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "GithubAction: Updated Latest Articles"
        file_pattern: 'data/blog/*.mdx'
        branch: main
        commit_author: Author <actions@github.com>
        skip_fetch: false
        skip_checkout: false