name: Frontend Update

defaults:
  run:
    working-directory: frontend
    
on:
  schedule:
    # Run at 7:37 PM CST every day
    - cron:  '37 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Cached Modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.lock') }}
      - name: Install
        run: npm i
      - name: Fetch Latest Articles
        run: npm run downloadArticles
      - name: Commit Latest Articles
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "danwakeem@gmail.com"
          git checkout --track origin/main
          git add ./data/blog
          git commit -am "GithubAction: Updated Latest Articles"
          git push origin HEAD:main