service: hugging-face-service

provider:
  name: aws
  runtime: python3.8
  architecture: arm64
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/sagemaker-lambda

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - '**/*'
  include:
    - headlines.py

functions:
  createHeadlinePredictor:
    handler: headlines.create
    timeout: 300
  getHeadline:
    handler: headlines.get_headline
    timeout: 300
  removeHeadlinePredictor:
    handler: headlines.remove
    timeout: 300
